# Generated by Django 4.1.3 on 2022-12-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=13)),
                ('fecha_nacimiento', models.DateField()),
                ('codigo', models.IntegerField()),
            ],
        ),
    ]
