# Generated by Django 4.1.3 on 2022-12-06 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='codigo',
        ),
    ]
